import http from 'http';
import AdmZip from 'adm-zip';

const PORT = 3000;
const JOB_ID = 'c3c6bbbd-5893-428d-9543-d42066e9ee34';

const server = http.createServer(async (req, res) => {
    console.log(`[MockServer] ${req.method} ${req.url}`);

    // Enable CORS/Headers
    res.setHeader('Access-Control-Allow-Origin', '*');

    if (req.method === 'GET' && req.url === `/api/jobs/${JOB_ID}`) {
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({
            id: JOB_ID,
            status: 'completed',
            version: '1.0.0',
            completedAt: new Date().toISOString(),
            timestamp: new Date().toISOString()
        }));
        return;
    }

    if (req.method === 'GET' && req.url === `/api/download/${JOB_ID}`) {
        const zip = new AdmZip();
        zip.addFile('manifest.json', Buffer.from(JSON.stringify({
            manifest_version: 3,
            name: "Mock Extension",
            version: "1.0.0",
            description: "Generated by Mock Server",
            action: {
                default_popup: "popup.html"
            }
        })));
        zip.addFile('popup.html', Buffer.from('<h1>Hello World</h1>'));

        const buffer = zip.toBuffer();
        res.writeHead(200, {
            'Content-Type': 'application/zip',
            'Content-Length': buffer.length
        });
        res.end(buffer);
        return;
    }

    res.writeHead(404);
    res.end();
});

server.listen(PORT, () => {
    console.log(`Mock server running at http://localhost:${PORT}`);
});
