import { ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Header } from '../layout/Header';
import { Footer } from '../layout/Footer';
import { StickyBackLink } from '../ui/StickyBackLink';

export function License() {
    return (
        <div className="min-h-screen flex flex-col bg-slate-50 dark:bg-zinc-950 text-slate-900 dark:text-slate-200 font-sans selection:bg-indigo-500/30">
            <Header />
            <StickyBackLink />

            <main className="flex-1 max-w-4xl mx-auto w-full px-6 pt-24 pb-12">
                <div className="mt-4 mb-8">
                    <Link to="/" className="inline-flex items-center gap-2 text-sm font-medium text-slate-500 hover:text-slate-900 dark:text-slate-400 dark:hover:text-white transition-colors">
                        <ArrowLeft size={16} /> Back to Home
                    </Link>
                </div>

                <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight mb-8 text-slate-900 dark:text-white">License</h1>
                <p className="text-lg text-slate-600 dark:text-slate-400 mb-12 leading-relaxed">
                    Open Source License Information
                </p>

                <div className="space-y-12">
                    <section>
                        <div className="p-6 md:p-8 rounded-2xl bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 shadow-sm font-mono text-sm leading-relaxed overflow-x-auto">
                            <p className="mb-4 font-bold text-slate-900 dark:text-white">MIT License</p>
                            <p className="mb-4">Copyright (c) {new Date().getFullYear()} EXTN Contributors</p>

                            <p className="mb-4">
                                Permission is hereby granted, free of charge, to any person obtaining a copy
                                of this software and associated documentation files (the "Software"), to deal
                                in the Software without restriction, including without limitation the rights
                                to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
                                copies of the Software, and to permit persons to whom the Software is
                                furnished to do so, subject to the following conditions:
                            </p>

                            <p className="mb-4">
                                The above copyright notice and this permission notice shall be included in all
                                copies or substantial portions of the Software.
                            </p>

                            <p>
                                THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
                                IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
                                FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
                                AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
                                LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
                                OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
                                SOFTWARE.
                            </p>
                        </div>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">Additional Licensing Information</h2>
                        <div className="prose prose-slate dark:prose-invert max-w-none text-slate-600 dark:text-slate-400">
                            <p>
                                Code generated by the EXTN platform is owned by the user who created it, as outlined in our Terms of Service. However, generated code may encompass open-source libraries or patterns which retain their respective licenses.
                            </p>
                        </div>
                    </section>
                </div>
            </main>

            <Footer />
        </div>
    );
}
