import { Cpu, ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';

export function TermsOfService() {
    return (
        <div className="min-h-screen bg-slate-50 dark:bg-zinc-950 text-slate-900 dark:text-slate-200 font-sans selection:bg-indigo-500/30">
            <header className="px-6 py-4 flex justify-between items-center border-b border-slate-200 dark:border-zinc-800 bg-white/50 dark:bg-zinc-950/50 backdrop-blur-md sticky top-0 z-50">
                <div className="flex items-center gap-2">
                    <Link to="/" className="flex items-center gap-2 group">
                        <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center text-white shadow-md shadow-indigo-500/20 group-hover:scale-105 transition-transform">
                            <Cpu className="w-5 h-5" />
                        </div>
                        <span className="text-xl font-bold tracking-tight text-slate-900 dark:text-white">
                            EXTN
                        </span>
                    </Link>
                </div>
                <Link to="/" className="text-sm font-medium text-slate-600 dark:text-slate-400 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors flex items-center gap-1">
                    <ArrowLeft size={16} /> Back to Home
                </Link>
            </header>

            <main className="max-w-4xl mx-auto px-6 py-12 md:py-20">
                <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight mb-8 text-slate-900 dark:text-white">Terms of Service</h1>
                <p className="text-lg text-slate-600 dark:text-slate-400 mb-12 leading-relaxed">
                    Last updated: December 13, 2025. Please read these terms carefully before using our services.
                </p>

                <div className="space-y-12">
                    <section>
                        <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">1. Acceptance of Terms</h2>
                        <div className="prose prose-slate dark:prose-invert max-w-none text-slate-600 dark:text-slate-400">
                            <p>
                                By accessing or using the EXTN AI Extension Builder ("the Service"), you agree to be bound by these Terms of Service. If you disagree with any part of these terms, you may not access the Service.
                            </p>
                            <p className="mt-4">
                                We reserve the right to modify these terms at any time. Your continued use of the Service following any changes indicates your acceptance of the new Terms of Service.
                            </p>
                        </div>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">2. Description of Service</h2>
                        <div className="prose prose-slate dark:prose-invert max-w-none text-slate-600 dark:text-slate-400">
                            <p>
                                EXTN provides an AI-powered platform for generating, testing, and downloading browser extensions. The Service utilizes advanced artificial intelligence models to interpret user prompts and generate functional code.
                            </p>
                            <p className="mt-4">
                                While we strive for accuracy, you acknowledge that AI-generated code may contain errors, vulnerabilities, or unintended behavior. You are solely responsible for reviewing, testing, and vetting any code generated by the Service before deployment or distribution.
                            </p>
                        </div>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">3. User Obligations</h2>
                        <div className="prose prose-slate dark:prose-invert max-w-none text-slate-600 dark:text-slate-400">
                            <p>You agree not to use the Service to:</p>
                            <ul className="list-disc pl-6 space-y-2 mt-4">
                                <li>Generate malicious code, malware, viruses, or spyware.</li>
                                <li>Create extensions that violate the policies of Chrome Web Store, Mozilla Add-ons, or other platforms.</li>
                                <li>Infringe upon the intellectual property rights of others.</li>
                                <li>Attempt to reverse engineer, decompile, or disrupt the Service.</li>
                            </ul>
                        </div>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">4. Intellectual Property</h2>
                        <div className="prose prose-slate dark:prose-invert max-w-none text-slate-600 dark:text-slate-400">
                            <p>
                                <strong>Your Content:</strong> You retain ownership of the prompts you input and the specific extensions you generate, subject to the rights of the underlying AI models and open-source libraries used.
                            </p>
                            <p className="mt-4">
                                <strong>Our Service:</strong> The EXTN platform, including its interface, proprietary algorithms, and branding, is protected by copyright and other intellectual property laws.
                            </p>
                        </div>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">5. Disclaimer of Warranties</h2>
                        <div className="prose prose-slate dark:prose-invert max-w-none text-slate-600 dark:text-slate-400">
                            <p className="uppercase tracking-wide font-semibold text-sm mb-2">The Service is provided "AS IS"</p>
                            <p>
                                WE MAKE NO WARRANTIES, EXPRESSED OR IMPLIED, REGARDING THE ACCURACY, RELIABILITY, OR SUITABILITY OF THE GENERATED CODE FOR ANY WRIT PURPOSE. WE EXPRESSLY DISCLAIM WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
                            </p>
                        </div>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">6. Limitation of Liability</h2>
                        <div className="prose prose-slate dark:prose-invert max-w-none text-slate-600 dark:text-slate-400">
                            <p>
                                IN NO EVENT SHALL EXTN BE LIABLE FOR ANY DAMAGES (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF DATA OR PROFIT, OR DUE TO BUSINESS INTERRUPTION) ARISING OUT OF THE USE OR INABILITY TO USE THE SERVICE, EVEN IF WE HAVE BEEN NOTIFIED OF THE POSSIBILITY OF SUCH DAMAGE.
                            </p>
                        </div>
                    </section>
                </div>

                <div className="mt-20 pt-8 border-t border-slate-200 dark:border-zinc-800 text-center text-slate-500">
                    <p>&copy; {new Date().getFullYear()} EXTN. All rights reserved.</p>
                </div>
            </main>
        </div>
    );
}
